"""Infer style, room and feel tags for the real catalogue. Run it yourself.

    uv run python -m scripts.derive_search_tags --i-have-authorization
    uv run python -m scripts.derive_search_tags --i-have-authorization --with-photos

It signs a real user in, reads the products that user is allowed to see through
the ordinary catalogue gateway, asks Gemini to label each one from its own
catalogue entry, and writes the result to seed/ as SQL. It writes nothing to
Supabase: a human reads the file and runs it, exactly as with every other
change to live data in this repository.

Two model calls per product by default (--runs), keeping only the tags most
runs agreed on: measured live, the model is stable on the sure tags and not on
the marginal ones. With --with-photos it also sends each product's primary
photograph, fetched through the same HTTPS allowlist the room preview uses,
which costs more and labels better.

Nothing it produces is presented as a seller's word. Every row lands in
product_search_tag with source = 'ai_inferred', and the API shows any reason
built from one as a guess.
"""

from __future__ import annotations

import argparse
import asyncio
import sys
from collections.abc import Sequence
from datetime import date
from pathlib import Path
from uuid import UUID

import httpx

from app.ai.provider import (
    AIProvider,
    AIProviderError,
    ImageBytes,
)
from app.ai.providers.gemini import build_gemini_provider
from app.ai.tagging import consensus, infer_tags, product_prompt
from app.auth.models import AuthenticatedRequestContext
from app.catalog.gateway import SupabaseCatalogueGateway
from app.catalog.normalization import InferredTag
from app.catalog.transform import is_recommendation_eligible
from app.catalog.upstream_models import UpstreamProduct
from app.config import load_ai_settings, load_settings
from app.rooms.images import ReferenceImageFetcher
from scripts.live_catalog_smoke import SmokeFailure, sign_in
from scripts.live_search_smoke import collect_credentials

ROOT = Path(__file__).resolve().parents[1]
PAGE_SIZE = 50


def sql_literal(text: str) -> str:
    """Quote a string for PostgreSQL by doubling its quotes."""

    return "'" + text.replace("'", "''") + "'"


def render_sql(
    tagged: Sequence[tuple[UpstreamProduct, tuple[InferredTag, ...]]],
    *,
    model_name: str,
    generated_on: date,
    with_photos: bool,
) -> str:
    """Render one reviewable, re-runnable file.

    Re-runnable matters: labelling improves, and the second run must replace
    the first rather than pile a second opinion on top of it. Every product
    that was looked at has its previous tags deleted, including the products
    the model declined to label, so a tag that is no longer believed goes away.
    """

    header = f"""\
/*
Inferred style, room and feel tags for {len(tagged)} product(s).

Generated by scripts/derive_search_tags.py on {generated_on.isoformat()} with
{model_name}, from each product's own catalogue entry\
{" and primary photograph" if with_photos else ""}.

These are the platform's guesses, not the sellers' words. They rank fuzzy
searches ("cosy", "for a reception") and never filter; the API caps their
weight below a seller-confirmed attribute and labels every reason built from
one as a guess.

Read it before running it. Requires migrations/product-search-tags-2026-09-20.sql.
Re-running replaces every tag of every product listed here.
*/

BEGIN;

SET LOCAL lock_timeout = '5s';
SET LOCAL statement_timeout = '2min';
"""

    lines = [header]
    identifiers = ",\n    ".join(f"'{product.id}'::uuid" for product, _ in tagged)
    lines.append(
        "DELETE FROM public.product_search_tag\n"
        f"WHERE product_id IN (\n    {identifiers}\n);\n"
    )
    rows: list[str] = []
    for product, tags in tagged:
        for tag in tags:
            rows.append(
                f"    ('{product.id}'::uuid, {sql_literal(tag.kind)}, "
                f"{sql_literal(tag.slug)}, {tag.confidence}, "
                f"{sql_literal(model_name)})"
            )
    if rows:
        lines.append(
            "INSERT INTO public.product_search_tag\n"
            "    (product_id, tag_kind, tag_slug, confidence, model_name)\n"
            "VALUES\n" + ",\n".join(rows) + ";\n"
        )
    else:
        lines.append("-- The model labelled nothing with enough confidence.\n")

    lines.append(
        f"""\
DO $search_tags_seed_check$
DECLARE
    stored bigint;
BEGIN
    SELECT pg_catalog.count(*) INTO stored
    FROM public.product_search_tag
    WHERE model_name = {sql_literal(model_name)};

    IF stored <> {len(rows)} THEN
        RAISE EXCEPTION USING MESSAGE =
            'Expected {len(rows)} inferred tag(s), found ' || stored;
    END IF;
END
$search_tags_seed_check$;

COMMIT;
"""
    )
    return "\n".join(lines)


async def photograph(
    product: UpstreamProduct, fetcher: ReferenceImageFetcher
) -> tuple[ImageBytes, ...]:
    """Fetch the product's primary photo, or nothing if it cannot be trusted."""

    images = sorted(
        product.images, key=lambda image: (not image.is_primary, image.display_order)
    )
    for image in images:
        fetched = await fetcher.fetch(str(image.image_url))
        if fetched is not None:
            return (fetched,)
    return ()


async def label_catalogue(
    *,
    context: AuthenticatedRequestContext,
    gateway: SupabaseCatalogueGateway,
    provider: AIProvider,
    fetcher: ReferenceImageFetcher | None,
    limit: int | None,
    runs: int,
) -> list[tuple[UpstreamProduct, tuple[InferredTag, ...]]]:
    products: list[UpstreamProduct] = []
    offset = 0
    while True:
        page = await gateway.list_products(
            authenticated_request=context, limit=PAGE_SIZE, offset=offset
        )
        eligible = [p for p in page[:PAGE_SIZE] if is_recommendation_eligible(p)]
        products.extend(eligible)
        if len(page) <= PAGE_SIZE:
            break
        offset += PAGE_SIZE
        if limit is not None and len(products) >= limit:
            break
    if limit is not None:
        products = products[:limit]

    print(f"{len(products)} product(s) to label\n")
    tagged: list[tuple[UpstreamProduct, tuple[InferredTag, ...]]] = []
    for index, product in enumerate(products, start=1):
        prompt = product_prompt(
            name=product.name,
            description=product.description,
            category=product.category.name,
            materials=product.materials,
            colours=tuple(colour.color_value for colour in product.colors),
        )
        photographs = await photograph(product, fetcher) if fetcher else ()
        try:
            # Several runs, then only what most of them agreed on. The model is
            # stable on the sure tags and not on the marginal ones, and these
            # rows are written once and then order everyone's results.
            answers = [
                await infer_tags(prompt, provider=provider, photographs=photographs)
                for _ in range(runs)
            ]
        except AIProviderError as error:
            print(f"  {index:>3}. {product.id} SKIPPED ({type(error).__name__})")
            continue
        tags = consensus(answers)
        tagged.append((product, tags))
        summary = ", ".join(f"{tag.slug} {tag.confidence}" for tag in tags) or "-"
        print(f"  {index:>3}. {product.id} {summary}")
    return tagged


async def run(arguments: argparse.Namespace) -> int:
    settings = load_settings()
    ai_settings = load_ai_settings()
    email, password = collect_credentials()

    async with httpx.AsyncClient() as client:
        provider = build_gemini_provider(client=client, settings=ai_settings)
        if provider is None:
            print("refusing: no GEMINI_API_KEY is configured", file=sys.stderr)
            return 2
        try:
            session, _ = await sign_in(
                client=client, settings=settings, email=email, password=password
            )
        except SmokeFailure as failure:
            print(f"refusing: sign-in failed ({failure})", file=sys.stderr)
            return 2

        context = AuthenticatedRequestContext(
            user_id=arguments.user_id, access_token=session.access_token
        )
        gateway = SupabaseCatalogueGateway(client=client, settings=settings)
        fetcher = (
            ReferenceImageFetcher(
                client=client,
                allowed_hosts=ai_settings.reference_hosts
                | {(settings.supabase_url.host or "").lower()},
            )
            if arguments.with_photos
            else None
        )
        tagged = await label_catalogue(
            context=context,
            gateway=gateway,
            provider=provider,
            fetcher=fetcher,
            limit=arguments.limit,
            runs=arguments.runs,
        )

    if not tagged:
        print("\nnothing was labelled; no file written")
        return 1

    destination = arguments.out or (
        ROOT / "seed" / f"search-tags-{date.today().isoformat()}.sql"
    )
    destination.write_text(
        render_sql(
            tagged,
            model_name=ai_settings.gemini_model,
            generated_on=date.today(),
            with_photos=arguments.with_photos,
        ),
        encoding="utf-8",
    )
    total = sum(len(tags) for _, tags in tagged)
    print(f"\nwrote {total} tag(s) for {len(tagged)} product(s) to {destination}")
    print("Read the file, then run it yourself in the Supabase SQL editor.")
    return 0


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--i-have-authorization",
        action="store_true",
        help="Required. This spends one model call per product.",
    )
    parser.add_argument(
        "--with-photos",
        action="store_true",
        help="Also send each product's primary photograph.",
    )
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument(
        "--runs",
        type=int,
        default=2,
        choices=(1, 2, 3),
        help="Label each product this many times and keep what most runs agreed "
        "on. Costs that many calls per product; 1 keeps whatever one run said.",
    )
    parser.add_argument("--out", type=Path, default=None)
    parser.add_argument(
        "--user-id",
        type=UUID,
        default=UUID("00000000-0000-0000-0000-000000000000"),
        help="Only labels the log line; the token decides what is readable.",
    )
    arguments = parser.parse_args(argv)
    if not arguments.i_have_authorization:
        print(
            "refusing: pass --i-have-authorization. This reads the live "
            "catalogue and spends one model call per product.",
            file=sys.stderr,
        )
        return 2
    return asyncio.run(run(arguments))


if __name__ == "__main__":
    raise SystemExit(main())
